//xianglei's analysis macro: analyze the picoDST generated by StV0Maker. 

#ifndef __CINT__
#include "TROOT.h"
#include "TMath.h"
#include "TSystem.h"
#include "TApplication.h"
#include "TFile.h"
#include "TError.h"
#include "TTree.h"
#include "TChain.h"
#include "TH1.h"
#include "TH2.h"
#include "TF1.h"
#include "TStyle.h"
#include "TCanvas.h"
#include "TString.h"
#include "Riostream.h"
#include <sstream>
#include <string>
#include <cstdlib>
#include "StThreeVectorF.hh"
#include "StPhysicalHelixD.hh"
//#include "StRefMultCorr/CentralityMaker.h"
//#include "StRefMultCorr/StRefMultCorr.h"
#include "v0dst.h"

TChain* ChainThem(const char* filelist, const char* treename, int nlist, int block);
#endif


//groups of runs
const int kGroup   = 1;
Double_t grpbd[kGroup+1]={0,17000000.};

const int kCentBin = 6;
Float_t  centbd[kGroup][kCentBin+1]={{48,61,77,97,121,153,500}};

const int kPtBin = 60;
Float_t  ptbd[kPtBin+1];

void cuts_la_cut0(int nlist, int block){

//the following will be loaded in .rootlogon.C in ACLIC mode
#ifdef __CINT__  
   //gSystem->Load("StRefMultCorr");
   gROOT->LoadMacro("TChainTool.C+");
   gROOT->LoadMacro("v0dst.C+");
#endif

   //StRefMultCorr* refmultCorrUtil = CentralityMaker::instance()->getRefMultCorr() ;

   TChain * tfg = ChainThem("finished_la.list","V0PicoDst",nlist,block);
   if(!tfg){ cout<<"ERROR: no files are added to the chain!"<<endl; return; }
   TChain * tbg = ChainThem("finished_larot.list","V0PicoDst",nlist,block);
   if(!tbg){ cout<<"ERROR: no files are added to the chain!"<<endl; return; }

   //histograms
   TString Dir("output/");
   TString Name("auau5.mb.la."); 
   TFile ohm(Dir+Name+Form("%d",nlist)+".cut0.histo.root","recreate");

   TH1F * hDays = new TH1F("Days","Days",1000,0,1000.0);
   TH1F * hMag = new TH1F("Mag","Magnetic Field",8000,-10,10.0);
   TH2F * hCirate = new TH2F("Cirate","Coincident rate (zdc vs bbc)",500,0,3000,500,0,30000);

   TH2D * hNRefMultNV0  = new TH2D( "RefMultV0", "Reference Multiplicity of selected events vs nV0", 600, 0.0, 600.0, 600,0,600.0 ) ;

   TH1F * hSelectNRefMult  = new TH1F( "SelectRefMult", "Reference Multiplicity of selected events", 1000, 0.0, 1000.0 ) ;
   TH1F * hSelectNRefMultCorr  = new TH1F( "SelectRefMultCorr", "Corrected Reference Multiplicity of selected events", 1000, 0.0, 1000.0 ) ;
   TH1F * hSelectVz = new TH1F( "SelectVz", "Vertex Z of selected events", 1000, 200, 220.0 ) ;

   Float_t pdgmass = 1.115684;
   Float_t masswidth = 0.1+0.01;
   //book histograms
   TH1F * hmInvMass = new TH1F("hmInvMass","Invariant mass", 440,pdgmass-masswidth,pdgmass+masswidth);
   TH1F * hmDca1to2 = new TH1F("hmDca1to2","Dca of daughters", 200,0,1.5);
   TH1F * hmDeclen = new TH1F("hmDeclen","Decay lenth of v0", 200,0,100);
   TH1F * hmV0Dca = new TH1F("hmV0Dca","Dca to PV of v0", 200,0,5.5);
   TH1F * hmDau1Dca = new TH1F("hmDau1Dca","Dca to PV of dau1", 200,0,15);
   TH1F * hmDau2Dca = new TH1F("hmDau2Dca","Dca to PV of dau2", 200,0,25);

   TH1F * hmNhitNfit = new TH1F("hmNhitNfit","Nhit - Nfit", 100,-50 ,50);

   TH1F * hmVz[kCentBin];
   for(Int_t iIM=0; iIM<kCentBin; iIM++){       
	TString hName("hmVz");
	hName = hName + "Cent" + Form("%d",iIM);
	TString hTitle("Vertex Z");
	hTitle = hTitle + " for centrality bin " + Form("%d",iIM);
	hmVz[iIM] = new TH1F(hName, hTitle, 700,200,220);
   }     

   TH1F * hmIM[kCentBin][kPtBin];
   TH1F * hmIMCent[kCentBin];
   TH1F * hmIMbg[kCentBin][kPtBin];
   TH1F * hmIMbgCent[kCentBin];
   for(Int_t iIM=0; iIM<kCentBin; iIM++){
	TString hName("hmInvMass");
	TString hTitle("Invariant mass for ");
	TString hNamebg = hName + "Bg" + "Cent" + Form("%d",iIM);
	hName = hName + "Cent" + Form("%d",iIM);
	hTitle = hTitle + "centrality bin " + Form("%d",iIM);
	hmIMCent[iIM] = new TH1F(hName, hTitle, 440, pdgmass-masswidth, pdgmass+masswidth);
	hmIMbgCent[iIM] = new TH1F(hNamebg, hTitle, 440, pdgmass-masswidth, pdgmass+masswidth);
	hmIMCent[iIM]->Sumw2();
	hmIMbgCent[iIM]->Sumw2();
	for(Int_t jIM=0; jIM<kPtBin; jIM++){
	   TString hName("hmInvMass");
	   TString hTitle("Invariant mass for ");
	   TString hNamebg = hName + "Bg" + "Cent" + Form("%d",iIM)  + "Pt" + Form("%d",jIM);
	   hName = hName + "Cent" + Form("%d",iIM) + "Pt" + Form("%d",jIM);
	   hTitle = hTitle + "centrality bin " + Form("%d",iIM) + " pt bin " + Form("%d",jIM);
	   hmIM[iIM][jIM] = new TH1F(hName, hTitle, 440, pdgmass-masswidth, pdgmass+masswidth);
	   hmIMbg[iIM][jIM] = new TH1F(hNamebg, hTitle, 440, pdgmass-masswidth, pdgmass+masswidth);
	   hmIM[iIM][jIM]->Sumw2();
	   hmIMbg[iIM][jIM]->Sumw2();
	}
   }

   //histogram for cent bin and pt bin
   TH1D * hmGroup = new TH1D("hmGroup","Run Group finder",kGroup,grpbd);
   TH1D * hmCent[kGroup];
   for(Int_t i=0;i<kGroup;i++){
	TString hName("hmCent");
	hName = hName + Form("%d",i);
	//TString hTitle("Centrality bin finder for group ");
	TString hTitle("Total number of events in centrality bins for group ");
	hTitle = hTitle + Form("%d",i);
	for(int j=0;j<kCentBin;j++)centbd[i][j] -= 0.1;
	hmCent[i] = new TH1D(hName,hTitle,kCentBin,centbd[i]);
	hmCent[i]->Sumw2();
   }
   for(int i=0;i<kPtBin+1;i++)ptbd[i]=i*0.1;
   TH1F * hmPt = new TH1F("hmPt","Pt bin finder",kPtBin,ptbd);

   for(Int_t ind = 0; ind < 2; ind++){
	//ind == 0, real data; ind == 1, rotation background
	TChain * t;
	if(ind ==0) t = tfg;
	else t = tbg;
	//bound them together
	v0dst dst(t);

	//event loop (copy from wrapper class' Loop method)
	Long64_t nentries = t->GetEntriesFast();
	Long64_t nbytes = 0, nb = 0;
	for (Long64_t jentry=0; jentry<nentries;jentry++) {
	   Long64_t ientry = dst.LoadTree(jentry);
	   if (ientry < 0) break;
	   nb = t->GetEntry(jentry);   nbytes += nb;
	   if(jentry%10000==0)cout<<jentry<<" "<<nentries<<endl;

	   //refmultCorrUtil->init(dst.runnumber);
	   //if ( refmultCorrUtil->isBadRun(dst.runnumber) ) continue;

	   //perform event cuts here
	   //if(fabs(dst.primvertexX*dst.primvertexX+dst.primvertexY*dst.primvertexY)>4.0)continue;
	   //if(fabs(dst.primvertexZ)>70)continue;
	   //if(fabs(dst.ntofmatched)<2.0)continue;
	   
	   //refmultCorrUtil->initEvent(dst.nrefmult, dst.primvertexZ) ;

	   if(ind==0)hDays->Fill((dst.runnumber%1000000)/1000);
	   if(ind==0)hMag->Fill(dst.magn);
	   if(ind==0)hCirate->Fill(dst.zdccirate,dst.bbccirate);

	   //fill histograms
	   if(ind==0)hSelectNRefMult->Fill(dst.nrefmult);
	   //if(ind==0)hSelectNRefMultCorr->Fill(refmultCorrUtil->getRefMultCorr());
	   if(ind==0)hSelectVz->Fill(dst.primvertexZ);

	   //find group 
	   Int_t grp = hmGroup->FindBin(dst.runnumber)-1;
	   //cout<<dst.runnumber<<" "<<grp<<endl;
	   if(ind==0)hmGroup->Fill(dst.runnumber);
	   if(grp<0 || grp >= kGroup) continue;

	   if(ind==0)hNRefMultNV0->Fill(dst.nrefmult,dst.nv0);

	   //find centbin
	   //Int_t centbin = hmCent[grp]->FindBin(refmultCorrUtil->getCentralityBin9())-1;
	   Int_t centbin = hmCent[grp]->FindBin(dst.nrefmult)-1;
	   if(centbin == kCentBin) {cout<<"ERROR in StRefMultCorr!"<<endl; break;}
	   //if(ind==0)hmCent[grp]->Fill(refmultCorrUtil->getCentralityBin9(),refmultCorrUtil->getWeight());
	   if(ind==0)hmCent[grp]->Fill(dst.nrefmult,1.0);
	   if(ind==0&&centbin>=0)hmVz[centbin]->Fill(dst.primvertexZ);

	   for(Int_t i=0;i<dst.nv0;i++){
		//fill histograms
		hmInvMass->Fill(dst.v0mass[i]);
		hmDca1to2->Fill(dst.dca1to2[i]);
		hmDeclen->Fill(dst.v0declen[i]);
		hmV0Dca->Fill(dst.v0dca[i]);
		hmDau1Dca->Fill(dst.dau1dca[i]);
		hmDau2Dca->Fill(dst.dau2dca[i]);

		hmNhitNfit->Fill(dst.dau1nhits[i]-dst.dau1tpc[i]);

		//cuts
		if(dst.v0rapidity[i]<-1.75)continue;
		if(dst.v0rapidity[i]>-1.50)continue;

		if(dst.v0declen[i]<3.0)continue;
		if(dst.dau1dca[i]<0.5)continue;
		if(dst.dau2dca[i]<1.5)continue;
		if(dst.v0dca[i]>0.8)continue;
		if(dst.dca1to2[i]>1.5)continue;
		if(dst.dau1nhits[i]<=10)continue;
		if(dst.dau2nhits[i]<=10)continue;
		if(dst.dau1pt[i]<0.05)continue;
		if(dst.dau2pt[i]<0.05)continue;
		if(fabs(dst.dau1nsigma[i])>4.0)continue;
		if(fabs(dst.dau2nsigma[i])>4.0)continue;
		if(1.0*dst.dau1nhits[i]/dst.dau1nhitsposs[i]<0.0)continue;
		if(1.0*dst.dau2nhits[i]/dst.dau2nhitsposs[i]<0.0)continue;
		if(dst.dau1nhitsdedx[i]<0)continue;
		if(dst.dau2nhitsdedx[i]<0)continue;

		StThreeVectorF PV(dst.primvertexX,dst.primvertexY,dst.primvertexZ);
		StThreeVectorF xv0(dst.v0x[i],dst.v0y[i],dst.v0z[i]);
		StThreeVectorF pv0(dst.v0px[i],dst.v0py[i],dst.v0pz[i]);
		StPhysicalHelixD helixv0(pv0,xv0,0,0);
		StThreeVectorF xv0toPV = xv0 - PV;
		double rdotp = xv0toPV.dot(pv0) ;
		//if(rdotp<=0)continue;
		if(rdotp<=0)continue;

		/*
		//veto lambda and Xi (proton from Lambda + bachelor pi-)
		double mMass1=0.93827;
		double mMass2=0.13957;
		double oe1 = sqrt(dst.dau1px[i]*dst.dau1px[i]+dst.dau1py[i]*dst.dau1py[i]+dst.dau1pz[i]*dst.dau1pz[i]+ mMass1*mMass1);
		double oe2 = sqrt(dst.dau2px[i]*dst.dau2px[i]+dst.dau2py[i]*dst.dau2py[i]+dst.dau2pz[i]*dst.dau2pz[i]+ mMass2*mMass2);
		double v0mass1 = sqrt(mMass1*mMass1 + mMass2*mMass2 + 2.*oe1*oe2 - 2.*(dst.dau1px[i]*dst.dau2px[i]+dst.dau1py[i]*dst.dau2py[i]+dst.dau1pz[i]*dst.dau2pz[i]));
		//if(fabs(v0mass1-1.1157)<0.015)continue;
		//if(v0mass1>1.1157-0.01 && v0mass1<1.165)continue;
		if(v0mass1>CutVetoLow && v0mass1<CutVetoHigh)continue;
		mMass1=0.13957;
		mMass2=0.93827;
		oe1 = sqrt(dst.dau1px[i]*dst.dau1px[i]+dst.dau1py[i]*dst.dau1py[i]+dst.dau1pz[i]*dst.dau1pz[i]+ mMass1*mMass1);
		oe2 = sqrt(dst.dau2px[i]*dst.dau2px[i]+dst.dau2py[i]*dst.dau2py[i]+dst.dau2pz[i]*dst.dau2pz[i]+ mMass2*mMass2);
		double v0mass2 = sqrt(mMass1*mMass1 + mMass2*mMass2 + 2.*oe1*oe2 - 2.*(dst.dau1px[i]*dst.dau2px[i]+dst.dau1py[i]*dst.dau2py[i]+dst.dau1pz[i]*dst.dau2pz[i]));
		//if(fabs(v0mass2-1.1157)<0.015)continue;
		//if(v0mass2>1.1157-0.01 && v0mass2<1.165)continue;
		if(v0mass2>CutVetoLow && v0mass2<CutVetoHigh)continue;
		*/

		//fill histograms
		if(centbin>=0){
		   //if(ind==0) hmIMCent[centbin]->Fill(dst.v0mass[i],refmultCorrUtil->getWeight());
		   //else hmIMbgCent[centbin]->Fill(dst.v0mass[i],refmultCorrUtil->getWeight());
		   if(ind==0) hmIMCent[centbin]->Fill(dst.v0mass[i],1.0);
		   else hmIMbgCent[centbin]->Fill(dst.v0mass[i],1.0);
		}
		Int_t ptbin = hmPt->FindBin(dst.v0pt[i])-1;
		if(ptbin==kPtBin)ptbin = -1;
		if(centbin<0 || ptbin<0)continue;
		//if(ind==0)hmIM[centbin][ptbin]->Fill(dst.v0mass[i],refmultCorrUtil->getWeight());
		//else hmIMbg[centbin][ptbin]->Fill(dst.v0mass[i],refmultCorrUtil->getWeight());
		if(ind==0)hmIM[centbin][ptbin]->Fill(dst.v0mass[i],1.0);
		else hmIMbg[centbin][ptbin]->Fill(dst.v0mass[i],1.0);
	   }
	}
	delete t;
   }

   ohm.Write();	//save all booked histograms
   ohm.Close();
}
