#!/bin/bash

#Generates a URQMD input file with a random seed

outDir=../urqmd_inputfiles/         #Path to the directory you want the input files to be saved to
eventsPerJob=10   #Number of events per job
nJobs=10000          #Number of jobs

#Make Sure the output Directory exists
if [ ! -d $outDir ]; then
    echo "ERROR: The output directory $outDir does not exist!"
    exit 1
fi

for ((x=0; x<$nJobs; x++))
do

suffix=`printf "%03d" $x`
name=$outDir/"AuAu_4pt5_FXT_URQMD_"$suffix.input
cat > $name <<EOF

#This input file was automatically generated by generateURQMDInputFiles.sh

#Define Collision System
pro 197 79
tar 197 79

#Define Number of Events per job
nev $eventsPerJob

#Define Impact Parameter
imp -3.4

#Define Collision Energy for fixed-target
#This needs to be the kinetic energy of the beam
ene 8.87

#Define the Time Evolution 
#200 fm/c ~ freezeout time
tim 200 200

#Define Equation of State
eos 0

#Generate the Random Seed
rsd $RANDOM

#Hydro Mode 0=Disabled, 1=Enabled
cto 45 0

#Change calculation frame: 0=Equal Velocity, 1=Target (Lab)
cto 27 1

#Supress Output to files
#f13
f14
f15
f16
f19
f20

xxx
EOF

done

echo "Finished creating the URQMD input files. Find them in the directory: "
echo "   " $outDir
